### ISSUE TITLE
Error in official documentation

### ISSUE THREAD

**Issue by winmasta** [horazont/aioxmpp#219]
In your official documentation in Quick Start section there is an error: "await client.send(msg)" returns an error "AttributeError: 'PresenceManagedClient' object has no attribute 'send'". It should be "await client.stream.send(msg)", then it works fine.

**Comment by horazont** [comment]
The documentation is correct, you’re looking at the wrong version. You are looking at the docs for the current devel branch, but you probably need the [documentation for the 0.9 release](https://docs.zombofant.net/aioxmpp/0.9/user-guide/quickstart.html).

Since 0.9, we added a send method to the client object, which is why it works in devel (and it indeed is the recommended way). Both ways work in devel. See also the (devel) documentation of [client.send](https://docs.zombofant.net/aioxmpp/devel/api/public/node.html#aioxmpp.Client.send) and [client.stream.send](https://docs.zombofant.net/aioxmpp/devel/api/public/stream.html#aioxmpp.stream.StanzaStream.send).
