### ISSUE TITLE
add a e2etest provisioner which works with prosody mod_auth_any

### ISSUE THREAD

**Issue by mwild1** [horazont/aioxmpp#237]
To more closely resemble a normal client connection, it would be great if the test suite worked with a list of normal credentials.

**Comment by horazont** [comment]
It’s probably best to distinguish between the ``mod_auth_any`` usecase, where aioxmpp could be generating random usernames for each test case (better isolation) and the "list of accounts" usecase, which might be harder to get right (because we might actually have to manually clear all the state between tests).

**Comment by mwild1** [comment]
Agreed, that's fine with me too (and on my todo list for scansion too).
