### ISSUE TITLE
Service and toposort, again

### ISSUE THREAD

**Issue by sebastianriese** [horazont/aioxmpp#258]
The toposort code is currently duplicated:

* `Client.summon` does a toposort on services on instanciation
* the `service.Meta` metaclass checks all services are toposortable and defines a total order on the services that is a valid toposort

While the latter feature makes debugging easier (by emitting an error at the definition of the class introducing the cycle), it has several problems:
* the run time is `O(N**2)` in the number of service classes `N`,  so it does not scale
* the total ordering information is only used for testing (and could be obtained there explicitly) and is otherwise useless and furthermore ill-defined (the topological sort is not unique). I think this feature should be removed.

The checking of the cycle-freeness can be substantially reduced, by only checking when the seldom used `ORDER_BEFORE` is used. Code using only `ORDER_AFTER` cannot introduce dependency loops (since the dependencies `ORDER_AFTER` has been declared before the current class even existed). So, it is sufficient to search through the dependency graph of the `ORDER_BEFORE` element to check for loops. This is only `O(n·m)` where `n` is the number of services actually in the dependency graph of that service and `m` is the average number of dependencies per service, instead of the total number of services!

**Comment by horazont** [comment]
The toposort in ``summon`` should be ``O(n)`` even if all services are summoned, because parts of the dependency graph which have been visited by previous ``summon`` invocations are not revisited (since each class is only instantiated once per client, and that check is made first and is an early-out). Even if you summon the services in extreme order (i.e. reverse or forward topological order).

Regarding the toposort in ``service.Meta``, that’s more interesting. Although it only affects startup time, I imagine it can become quite interesting rather soon, because we do it at each service class definition.

I agree with you w.r.t. ``ORDER_AFTER``, since it can only be set at class definition time, it is not possible to create loops using that. I think you might be right on ``ORDER_BEFORE`` needed to be set on a class in order for a dependency loop to be created by the definition of that class.

I am not 100% sure on that though. So unless we have a mathematical proof for that, I’d like to have the current full toposort as a testutils function which we can invoke in the tests to ensure that the service topology is safe (so that we don’t make a release with a dependency loop by accident...).

**Comment by horazont** [comment]
This is fixed with #273, right?

**Comment by sebastianriese** [comment]
Yup.
