### ISSUE TITLE
XEP-0027 OpenPGP for messaging and presence (xep-implementation )

### ISSUE THREAD

**Issue by pggdt** [horazont/aioxmpp#297]
[XEP-0027: Current Jabber OpenPGP Usage](https://xmpp.org/extensions/xep-0027.html)

**Comment by horazont** [comment]
@pggdt The implementation of XEP-0027 in aioxmpp would be limited to declaring the schema, like we do for XEP-0203 (Stanza Forwarding) or (at the moment) XEP-0333 (Chat Markers).

Just saying this here so that we’re on the same page. Integrating actual E2EE with the message flow is left to the application, since there are too many ways to do this sensibly.

**Comment by horazont** [comment]
In addition, note that XEP-0027 is vulnerable to trivial injection attacks, because messages are only encrypted, not signed.

**Comment by horazont** [comment]
@pggdt Could you review and/or test #299?

**Comment by pggdt** [comment]
thank you horazont
