### ISSUE TITLE
0.12.0 cannot connect

### ISSUE THREAD

**Issue by pszafer** [horazont/aioxmpp#355]
Hi,
With the newest aioxmpp/py39 I can't connect to xmpp server.
End up with message:
```
ERROR:asyncio:Future exception was never retrieved
future: <Future finished exception=ConnectionError('stream shut down')>
ConnectionError: stream shut down
```

**Comment by horazont** [comment]
Please answer the following questions:

- What have you tried? (preferably with code)
- What happened? (preferably with logs)
- What did you expect to happen instead?

Specifically, the message there is not necessarily an error depending on how you set up the stream. It indicates that the stream was closed without a specific error.

**Comment by pszafer** [comment]
Here is code I'm running.
Same code with Python3.8 + aioxmpp 0.11 is working
Python3.8 with aioxmpp 0.12 not working
python3.9 with aioxmpp 0.11 not working as bug before
py3.9 with aioxmpp 0.12 not working.

should I set up stream somehow different for 0.12?

**Comment by pszafer** [comment]
@horazont how can I find out why in the 0.12 version of lib stream is closed on?

maybe I should add that stream is closed during initial connection
```
async with self.xmppclient.connected():
```

**Comment by horazont** [comment]
@pszafer Sorry for the brief reply last night, I was tired and short on time. (I’m in UTC+1 timezone.)

So looking at the code, I can not spot anything obviously wrong. aioxmpp 0.12.0 also passed the very extensive test suite which connects to prosody and ejabberd servers and validates a lot of things (with python 3.5 through python 3.9). I am also using it with python 3.9 regularly to do various things. There are no breaking changes in 0.12.0 except the drop of python <3.5 support.

So I’m fairly confident that it’s working alright in general.

To figure out why it is not working for you, I’d need debug logs from aioxmpp, including the XML logs from the XMLStream, ideally including the debug logs from your code so that I can see where it’s heading wrong.

Can you provide that?

Thanks!

**Comment by pszafer** [comment]
don't worry. we're in same timezone ;)
funny/weird story, I had error like above for another 5 times, until I started redirecting stdout and stderr to file
```
xmpp_file.py 2>&1 debug.log
```

from then I go into infinite loop and I see same error just after clicking CTRL+C
```
ERROR:asyncio:Future exception was never retrieved
```

this is full log as for now
[out.log](https://github.com/horazont/aioxmpp/files/5834503/out.log)

is it enough?
would you like to have logs from working environment with aioxmpp 0.11 ? maybe it will help somehow to see the difference?

**Comment by horazont** [comment]
Hi!

Did you notice that your application is throwing an exception there?

```
  File "/home/poznan.tbhydro.net/admin/Projekty/prywatne/bosch-thermostat-client-python/bosch_thermostat_client/bosch_rawscan_cli.py", line 63, in cli
    if await gateway.check_connection():
  File "/home/poznan.tbhydro.net/admin/Projekty/prywatne/bosch-thermostat-client-python/bosch_thermostat_client/gateway/base_gateway.py", line 234, in check_connection
    await self.initialize()
  File "/home/poznan.tbhydro.net/admin/Projekty/prywatne/bosch-thermostat-client-python/bosch_thermostat_client/gateway/base_gateway.py", line 61, in initialize
    await self._update_info(initial_db.get(GATEWAY))
  File "/home/poznan.tbhydro.net/admin/Projekty/prywatne/bosch-thermostat-client-python/bosch_thermostat_client/gateway/ivt_gateway.py", line 57, in _update_info
    response = await self._connector.get(uri)
  File "/home/poznan.tbhydro.net/admin/Projekty/prywatne/bosch-thermostat-client-python/bosch_thermostat_client/connectors/xmpp.py", line 115, in get
    raise DeviceException(f"Error requesting data from {path}")
  File "/home/poznan.tbhydro.net/admin/Projekty/prywatne/bosch-thermostat-client-python/venv/lib/python3.9/site-packages/aioxmpp/node.py", line 1672, in __aexit__
    self._client.stop()
  File "/home/poznan.tbhydro.net/admin/Projekty/prywatne/bosch-thermostat-client-python/venv/lib/python3.9/site-packages/aioxmpp/node.py", line 1057, in stop
    self.logger.debug("stopping main task of %r", self, stack_info=True)
2021-01-19 09:12:30,131:INFO:aioxmpp.node.PresenceManagedClient:client shutting down (on request)
```

The stream is being shut down ("on request", because it is at the end of the `async with` block) after the `DeviceException` was thrown.

It seems as if the stream is properly shut down then, and then another attempt is made, where the same thing happens. This happens a bunch of times.

The last attempt seems to be interrupted while it is authenticating. Was that because you hit C-c or for another reason?

**Comment by horazont** [comment]
Note that you see the `async with` in the traceback, but it is a little misleading. It is actually processing the **exit** of that block, not the enter. There is not really a way to see that from the single traceback line alone, but you can see that it is shutting down via ``__aexit__`` in the traceback.

**Comment by pszafer** [comment]
hi, thanks for response.
it started working today, so it must be something with their xmpp servers.
thank you for your help.

I'd like to ask one question though as you're an expert.
bosch xmpp protocol is just wrapper around HTTP request, so I send through XMPP message `GET /temperature`
and I need to wait for response.

is it good approach
```python
def message_received(self, msg):
  do_something_with_message...
  self.msg_event.set()

self.message_dispatcher.register_callback(
            aioxmpp.MessageType.NORMAL,
            None,
            self.message_received,
        )
self.message_dispatcher.register_callback(
    aioxmpp.MessageType.CHAT,
    None,
    self.message_received,
)
await self.xmppclient.send(self._build_message(
    method=GET,
    path=path))
await asyncio.wait_for(self.msg_event.wait(), self._request_timeout)
self.unregister_callbacks()
```

or is there any better way to send xmpp message and `await` for response from server.

**Comment by horazont** [comment]
>  it started working today, so it must be something with their xmpp servers.

Thanks for the update!

> I'd like to ask one question though as you're an expert.
> […]

Ah, I saw that. Here’s some feedback:

1. If you can, keep your XMPP connection open in the background, it’s a lot cheaper than re-opening and re-authenticating the stream all the time. aioxmpp will automatically reconnect if there’s a problem (and you can configure the ping timeouts and whatnot to control how quickly it reacts to outages).
2. Use a Future instead of an Event for this; Futures allow for a return value and are single-use (so you get strong exceptions when you have a mistake in your code).
3. Keep the handlers registered, even if you don’t let the XMPP connection live all the time.
4. If you can and the protocol allows for it, match on the ID to avoid being confused by foreign messages.

(Note: In XMPP, the protocol you described would be done with IQs instead of Messages, but I guess that was Bosch’s terrible choice. There is even a standard way to map HTTP to XMPP: https://xmpp.org/extensions/xep-0332.html (not supported in aioxmpp though))

**Comment by pszafer** [comment]
> 1. If you can, keep your XMPP connection open in the background, it’s a lot cheaper than re-opening and re-authenticating the stream all the time. aioxmpp will automatically reconnect if there’s a problem (and you can configure the ping timeouts and whatnot to control how quickly it reacts to outages).

I will do that. Do I need to unregister manually if app is going to be closed?

> 2. Use a Future instead of an Event for this; Futures allow for a return value and are single-use (so you get strong exceptions when you have a mistake in your code).
ok.
> 3. Keep the handlers registered, even if you don’t let the XMPP connection live all the time.
ok.
> 4. If you can and the protocol allows for it, match on the ID to avoid being confused by foreign messages.
Bosch always return None in message id, so I don't see anyway to avoid foreign messages.
> 
> (Note: In XMPP, the protocol you described would be done with IQs instead of Messages, but I guess that was Bosch’s terrible choice. There is even a standard way to map HTTP to XMPP: https://xmpp.org/extensions/xep-0332.html (not supported in aioxmpp though))

This is response from bosch server:
```
 <message from='gateway_1111111@wa2-mz36-qrmzh6.bosch.de/iCom-RestApi' to='contact_1111111@wa2-mz36-qrmzh6.bosch.de/atvxt40mjn' id=None type=<MessageType.NORMAL: 'normal'>>
```

where `1111111` is serial number of thermostat. (I sent message with id:
```
<message from=None to='gateway_1111111@wa2-mz36-qrmzh6.bosch.de' id=':tMeSCCc5idLemBkr5UQ5' type=<MessageType.CHAT: 'chat'>>
```
)

and body of the response looks like:
```
['HTTP/1.0 200 The request has succeeded', 'Content-Type: application/json', '', '', 'kr6OwC3Iw0ljU9c5mRlIqGjlsUchm4r8nhozX3OpMiCcxCoAPBmPwmFdo1IrLez1enwvJLaIsCm113JhXHU7F2RRuo5CVGzSgvsywUEr1BPMm4UF3hPIwGKrG64yw+8S19Tn/v1F+osxavqa9J/T134tadKektluAATuV5J1ok+76VvNjsTGs50L4/YzsOIqBaoMHNUx3T5QCZBe/TVs9VjMvI0LxiZa3zeB37CaQBrq35j0G6E4oFHxHTWl0S0IpMm9iNPNllKa04vnrfNJwOzpecC5k2Ay/prdBqAyauc+3TLWTAm4Iuk84pM4fG68P0VpXhFLKmmxbQdJEk0P+aYfLqREkla87TD80Hg0yH0=']
```

last line of the array is decrypted to:
```
{'id': '/system/brand', 'type': 'stringValue', 'writeable': 0, 'recordable': 0, 'value': 'Buderus', 'allowedValues': ['unknown', 'Bosch', 'Junkers', 'Buderus', 'Nefit', 'Sieger', 'Tata', 'Dakon', 'Elm', 'Boulter', 'Vulcano', 'Worcester', 'British Gas', 'IVT', 'Geminox', 'Neckar', 'Zeus', 'Milton']}
```

so only way to know if the response is for query I sent is to compare query to id found in decrypted json.

**Comment by horazont** [comment]
Yeah, I suppose you’ll have to match on the stuff deep in the JSON payload then, but at least you have *something* to match on :)

**Comment by horazont** [comment]
Sorry, didn’t see your other question:

>> If you can, keep your XMPP connection open in the background, it’s a lot cheaper than re-opening and re-authenticating the stream all the time. aioxmpp will automatically reconnect if there’s a problem (and you can configure the ping timeouts and whatnot to control how quickly it reacts to outages).
> 
> I will do that. Do I need to unregister manually if app is going to be closed?

No, you do not need to unregister handlers. You only need to properly shut down the stream (trivial if you use `async with`, but you can also use `.start()` and `.stop()` on the client).

**Comment by pszafer** [comment]
Thanks!
Do you have by any chance some examples using asyncio.Future with your lib? I see you use a lot of this in lib code, but I can't find anything useful in examples?
I'm trying to switch to Future, but I'm doing something wrong.
It gets data but I got a lot of:
```
ERROR:asyncio:Future exception was never retrieved
future: <Future finished exception=ConnectionError('stream shut down')>
```
in logs.
