### ISSUE TITLE
Installation in a virtualenv on Xubuntu 14.04

### ISSUE THREAD

**Issue by FriendFX** [horazont/aioxmpp#38]
Either I am doing something incorrect, or the [installation instructions](https://github.com/horazont/aioxmpp/blob/devel/docs/user-guide/installation.rst) could use some additions:

To get `pip3 install aioxmpp` to complete without errors, I had to do `sudo apt-get install libssl-dev`.

Being somewhat inexperienced with pip3, python3 and the `cryptography` python package, I am not 100% sure I did the right thing.

Could someone confirm this is OK?

**Comment by horazont** [comment]
Yes, you need to have libssl-dev installed to install cryptography and PyOpenSSL. You also need to have a whole bunch of other packages installed, such as python3-dev and so on, which I do not list explicitly.

I only mention libxml2-dev explicitly because it is non-obvious that its needed (pip install would succeed, but the package wouldn’t work).

**Comment by horazont** [comment]
I added a few words to the installation instructions.
