### ISSUE TITLE
simple example

### ISSUE THREAD

**Issue by dPeS** [horazont/aioxmpp#6]
with few lines of code for sending simple msg will be very helpfull, thanks

**Comment by horazont** [comment]
I made you this: https://github.com/horazont/aioxmpp/blob/devel/examples/send_message.py

Please see the comment in that file, which details on the reasons why it is so long and cumbersome and what I plan to do against it.

Thanks for asking for that example, it definitely gave me some ideas what needs to be improved in the API!

Let me know what you think about the matters and thanks for your interest in aioxmpp.

**Comment by dPeS** [comment]
great! thanks

**Comment by horazont** [comment]
@dPeS I fixed two typos which caused tracebacks after the message was sent. Should be working now.

**Comment by horazont** [comment]
I implemented a few things, which are still in the devel branch. Unfortunately, a new release isn’t going to happen anytime soon, since I plan to integrate PubSub support and that is quite a lot of work.

The things I mentioned allow for a much shorter send_message.py, check it out: <https://github.com/horazont/aioxmpp/blob/devel/examples/send_message.py>.

**Comment by dPeS** [comment]
super, thanks! could be closed now imo
