### ISSUE TITLE
Refactor xso.types.AbstractType

### ISSUE THREAD

**Issue by sebastianriese** [horazont/aioxmpp#92]
xso.types.AbstractType is currently used for two orthogonal use cases: Parsing and formatting string payload and parsing and formatting XSOs. Those uses should be split on two base classes.

**Comment by horazont** [comment]
I started to work on this in ``feature/refactor-AbstractType``. However, I came across the following:

EnumType allows for a ``nested_type`` argument to describe the conversion of XML (character or element) data to the type accepted by the constructor of the enum. Currently, EnumType can be used for both ChildValueMap-like descriptors and Text-like descriptors, if the ``nested_type`` is chosen correctly.

Refactoring AbstractType into AbstractCDataType and AbstractElementType would require to modify EnumType in one of the following ways:

1. Split EnumType in two classes (one inheriting from AbstractCDataType and one inheriting from AbstractElementType).

   Advantages: 
   * allows for early checking for correct interface being used as ``nested_type``.
   * feels like the "clean" solution.

   Disadvantages: 
   * possible code duplication
   * requires changes where EnumType is used (can be worked around by providing a EnumType function which picks the correct class depending on the ``nested_type`` argument, defaulting to EnumCDataType)

2. Modify EnumType to provide *both* interfaces at the same time.

   Advantages:
   * compatibility

   Disadvantages:
   * this feels like a nasty hack
   * incorrect ``nested_type`` would not be detected until the interface is used (because EnumType cannot know how it will be used) (this is also that way currently)

I tend to go for route (1) and provide the EnumType function to work around the compatibility issues.
